apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitcoind.persistentStorageName" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
  annotations:
    k8up.syn.tools/backup: "true"
    {{- include "bitcoind.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
