apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
  annotations:
    {{- include "bitcoind.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: json-rpc
      protocol: TCP
      name: json-rpc
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}
