apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "public-pool.persistentStorageName" . }}
  labels:
    {{- include "public-pool.labels" . | nindent 4 }}
  annotations:
    k8up.syn.tools/backup: "true"
    {{- include "public-pool.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bulk
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
