apiVersion: v1
kind: Service
metadata:
  name: {{ include "public-pool.fullname" . }}
  labels:
    {{- include "public-pool.labels" . | nindent 4 }}
  annotations:
    {{- include "public-pool.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3333
      targetPort: stratum
      protocol: TCP
      name: stratum
    - port: 3334
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "public-pool.selectorLabels" . | nindent 4 }}
