routesAutogeneratePrefixes:
  - www
project: myexample-project
environment: environment-with-really-really-reall-3fdb
environmentType: development
namespace: myexample-project-environment-with-really-really-reall-3fdb
buildType: branch
lagoonVersion: v2.x.x
kubernetes: lagoon.local
routesAutogenerateInsecure: "true"
routesAutogenerateEnabled: "true"
routesAutogeneratePrefixHyphens: "false"
prNumber: 1234
prBaseBranch: main
prHeadBranch: main
